language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

env:
  matrix:
    - DJANGO=1.8
    - DJANGO=1.9
    - DJANGO=1.10
    - DJANGO=1.11
    - DJANGO=2.0
    - DJANGO=master

install:
  - TOX_ENV=py${TRAVIS_PYTHON_VERSION}-django${DJANGO}
  - pip install tox
  - tox -e $TOX_ENV --notest

script:
  - tox -e $TOX_ENV

after_success:
  - tox -e $TOX_ENV -- pip install coveralls 
  - tox -e $TOX_ENV -- coveralls $COVERALLS_OPTION

matrix:
  allow_failures:
    - python: "pypy3"
    - env: DJANGO="2.0
    - env: DJANGO="master"
  exclude:
    - python: "2.7"
      env: DJANGO=2.0
    - python: "2.7"
      env: DJANGO=master
    - python: "3.4"
      env: DJANGO=2.0
    - python: "3.4"
      env: DJANGO=master
